### ISSUE TITLE
Bug - "Press R to cancel replay" hud text not disappearing sometimes

### ISSUE THREAD

**Issue by Mykybo** [WelkinU/OverwatchWorkshopScripts#5]
The hud text "Press R to cancel replay" stays permanently on-screen, see screenshot below.

![image](https://user-images.githubusercontent.com/9023791/115847158-f28b7080-a422-11eb-91ab-5c0ce28b2e01.png)

**Comment by WelkinU** [comment]
Do you know what scenarios this occurs in? Is it in scenarios with high server load (a lot of people in the lobby or after a lot of checkpoints are created leading to large replay arrays)? 

I haven't seen this happen so far, and it looks like the code should make sure that Progress Bar gets deleted. (Code that uses the variable Event Player.MenuTextIDTempStore is prevented from executing at same time, so that shouldn't be an issue). Maybe if someone starts viewing pioneer replay at the exact moment you pioneer, it could get mixed up?

https://github.com/WelkinU/OverwatchWorkshopScripts/blob/70b547822b187a2f5e9e8f50131ee0baab1d5811/DoomfistParkour/DoomPioneerParkour.txt#L568-L584
